networks:
  postgres:
    external: false

volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: waitingway
      POSTGRES_PASSWORD: waitingway_passwd
      POSTGRES_DB: waitingway
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
  waitingway:
    image: ghcr.io/workingrobot/waitingway-web:latest
    restart: unless-stopped
    volumes:
      - ./docker-config.yml:/app/config.yml:ro
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off 127.0.0.1:3000/api/v1 || exit 1']
    networks:
      - postgres
    depends_on:
      - db
    # Ideally, you would put this behind a reverse proxy, like nginx
    ports:
      - 3000:3000