volumes:
  wway-pg-data:
    driver: local

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: waitingway
      POSTGRES_PASSWORD: waitingway_passwd
      POSTGRES_DB: waitingway
    volumes:
      - wway-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
