networks:
  postgres:
    external: false

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: waitingway
      POSTGRES_PASSWORD: waitingway_passwd
      POSTGRES_DB: waitingway
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
  waitingway:
    build: .
    restart: unless-stopped
    env_file:
      - .docker.env
      - .secrets.env
    networks:
      - postgres
    ports:
      - 3000:3000